### ISSUE TITLE
Could you please delete all inaproppriate bostohn.dat in the quantnet? Then it'll be clear where is necessary datafile.

### ISSUE THREAD

**Issue by polarstern** [QuantLet/QID-904-MVAppsib#3]
That's why now I can't address this issue to Theo...

**Comment by lborke** [comment]
Done!
Now there is only one bostonh.dat in the QN and I have corrected it.
It runs with all Qs from QNet, R and Matlab.
You can check it, too.

**Comment by polarstern** [comment]
Thanks! Yes, it runs.
